---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Check for Python
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python
  - name: Install Python
    raw: yum -y install python
    when: check_python.rc != 0
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Pull DockerImage
    command: docker pull devopsedu/webapp:latest 
  - name: run Image
    command: docker run -itd -P devopsedu/webapp:latest 
