---
- hosts: webservers
  become: true
  become_user: root
  vars :
   mytext: |
     [google-chrome]
     name=google-chrome
     baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
     enabled=1
     gpgcheck=1
     gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
   updatetest : |
  tasks:
  - name: Check for Python (added this for checking my understandin, I know this is not require for this project)
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python
  - name: Install Python (Added for my udnerstanding not required for this project)
    raw: yum -y install python
    when: check_python.rc != 0
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: Creating a file with content
    file:
     path: "/etc/yum.repos.d/google-chrome.repo"
     mode: 0777
     owner: root
     state: touch
  - name: create File content
    copy:
      dest: "/etc/yum.repos.d/google-chrome.repo"
      content: "{{ mytext }}"
  - name: Install Chrome
    yum:
     name: google-chrome-stable
     state: present
     update_cache: yes
  - name: Epel-release
    yum:
     name: epel-release
     state: present
     update_cache: yes
  - name: install chromium
    yum:
     name: chromium
     state: present
  - name: chromedriver
    yum:
     name: chromedriver
     state: present  
  - name: get the dockerfile from githib
    git: repo=https://github.com/itforankit2021/MyCertProject.git dest=/tmp/gitrepo
  - name: create DockerImage
    command: chdir=/tmp/gitrepo/projCert docker build -t myimage:latest .
  - name: run Image
    command: docker run -itd -P myimage:latest

